server:
  port: 80
  host: localhost
spring:
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.jc.jdbc.Driver
      url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=utf8
      username: root
      password: root

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tb_
#  mapper-locations: classpath*:XmlMapper/*Mapper.xml